version: '3.9'

networks:
  zeebe_network:

volumes:
  zeebe_data:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

services:
  zeebe:
    image: camunda/zeebe:8.1.6
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_BROKER_EXPORTERS_KAFKA_CLASSNAME=hu.dpc.rt.kafkastreamer.exporter.KafkaExporter
      - ZEEBE_BROKER_EXPORTERS_KAFKA_JARPATH=/exporter.jar
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_JARPATH=/exporter.jar
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=hu.dpc.rt.kafkastreamer.exporter.NoOpExporter
    ports:
      - "26500:26500"
      - "9600:9600"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9600/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m30s
    volumes:
      - zeebe_data:/usr/local/zeebe/data
      - ./zeebe-config.yaml:/usr/local/zeebe/config/application.yaml
      - /home/amydoxym/Documents/dev/Git/OAF/PaymentHub/ph-ee-exporter/kafka-clients-2.4.0.jar:/usr/local/zeebe/lib/kafka-clients-2.4.0.jar
      - /home/amydoxym/Documents/dev/Git/OAF/PaymentHub/ph-ee-exporter/target/exporter-1.0.0-SNAPSHOT.jar:/exporter.jar
    networks:
      - zeebe_network

  zeebe_ops:
    image: oaftech.azurecr.io/phee-ns/phee-zeebe-ops:v1.0.1
    ports:
      - "5001:5000"
    environment:
      ZEEBE_BROKER_CONTACTPOINT: zeebe:26500
      LOGGING_LEVEL_ROOT: INFO
    depends_on:
      zeebe:
        condition: service_healthy
    networks:
      - zeebe_network

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - zeebe_network

  kafka:
    container_name: kafka
    image: docker.io/bitnami/kafka:2
    ports:
      - "9094:9094"
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=INTERNAL://kafka:9092,OUTSIDE://kafka:9094
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    depends_on:
      - zookeeper
    networks:
      - zeebe_network

  kafka-ui:
    image: docker.redpanda.com/redpandadata/console:latest
    ports:
      - "9095:8080"
    environment:
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - zeebe_network

  channel-connector:
    image: oaftech.azurecr.io/oneacrefund/channel-connector:1.1.1-mifos-1.5.3
    ports:
      - "8082:8080"
      - "5002:5000"
    environment:
      AMS_GROUPS_0__IDENTIFIER: FINERACTACCOUNTID
      AMS_GROUPS_0__VALUE: fineract
      DFSPIDS: oaf,oafrw,rw-oaf
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_PATTERN_CONSOLE: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
      MPESA_NOTIFICATION_FAILURE_ENABLED: false
      MPESA_NOTIFICATION_SUCCESS_ENABLED: false
      ZEEBE_BROKER_CONTACTPOINT: zeebe:26500
      BPMN_FLOW_MOMO-FLOW: "momo_flow_{ams}-{dfspid}"
    depends_on:
      zeebe:
        condition: service_healthy

  tnm-mw-connector:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5000"
    environment:
      ZEEBE_BROKER_CONTACTPOINT: zeebe:26500
      CHANNEL_HOST: "http://channel-connector:8080"
    depends_on:
      zeebe:
        condition: service_healthy

  fineract-ams:
    image: oaftech.azurecr.io/oneacrefund/ph-ee-connector-ams-fineract:0.0.5
    ports:
      - "8084:5004"
      - "5004:5000"
    environment:
      AMS_LOCAL_ENABLED: true
      FINERACT_BASE-URL: https://loans.test.oneacrefund.org/fineract-provider/api/v1
      LOGGING_LEVEL_ROOT: INFO
      SPRING_PROFILES_ACTIVE:
      ZEEBE_BROKER_CONTACTPOINT: zeebe:26500
      LOGGING_PATTERN_CONSOLE: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,loggers
    depends_on:
      zeebe:
        condition: service_healthy
    networks:
      - zeebe_network

  operations-mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
    networks:
      - zeebe_network

  rdbms-importer-rdbms:
    image: oaftech.azurecr.io/oneacrefund/ph-ee-importer-rdbms:1.0.0-mifos-1.3.1
    restart: always
    environment:
      LOGGING_LEVEL_ROOT: info
      DATASOURCE_CORE_HOST: operations-mysql
      DATASOURCE_CORE_USERNAME: root
      DATASOURCE_CORE_PASSWORD: mysql
      DATASOURCE_CORE_SCHEMA: tenants
      KAFKA_BROKERS: http://kafka:9092
      BPMN_PROCESSES_0__ID: "inbound_tnm_fineract"
      BPMN_PROCESSES_0__DIRECTION: "$${bpmn.incoming-direction}"
      BPMN_PROCESSES_0__TYPE: "$${bpmn.transfer-type}"
    ports:
      - "5007:3306"
    depends_on:
      - operations-mysql
    networks:
      - zeebe_network

  operations-app:
    image: oaf--ph-ee-operations-app-operations-app:latest
    ports:
      - 5006:5000
    environment:
      FINERACT_DATASOURCE_CORE_HOST: operations-mysql
      SPRING_PROFILES_ACTIVE: bb
      TENANTS: oaf
    depends_on:
      - operations-mysql
      - rdbms-importer-rdbms
    networks:
      - zeebe_network
